services:
  k8s-docs-app:
    build: .
    platform: linux/amd64
    image: maayanlab/k8s-docs:0.3.4
    pull_policy: missing
    restart: unless-stopped
    ports:
    - 80:80
    x-kubernetes:
      imagePullPolicy: IfNotPresent
      annotations:
        maayanlab.cloud/ingress: https://docs.k8s.dev.maayanlab.cloud
x-kubernetes:
  name: k8s-docs
